
//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     Mudanças neste arquivo podem causar comportamento incorreto e serão perdidas
//     quando o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
module Api.Produto.Delete {
    export interface Command {
        id: number;
    }
}

module Api.Produto.InsertEdit {
    export interface Command {
        id?: number;
        descricao?: string;
        valor: number;
    }

    export interface Query {
        id: number;
    }
}

module Api.Produto.List {
    export interface Dto {
        products?: ProductDto[];
    }

    export interface ProductDto {
        id: number;
        descricao?: string;
        valor: number;
    }

    export interface Query {
    }
}

export default Api
